name: Deploy App to Posit Connect - PROD
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set Up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
      - name: Install and Load rsconnect
        run: R -e "install.packages('rsconnect'); library(rsconnect)"
        
      - name: Install R Packages
        run: |
          R -e "install.packages(c(
            'DBI',
            'DT',
            'KernSmooth',
            'MASS',
            'Matrix',
            'R6',
            'RColorBrewer',
            'Rcpp',
            'askpass',
            'backports',
            'base64enc',
            'bit',
            'bit64',
            'blob',
            'brew',
            'broom'
          ))"
        
      - name: Change Directory and Write Manifest
        run: |
          cd ./Production
          R -e "rsconnect::writeManifest()"
          
      - name: Commit Manifest
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add "./Production/manifest.json"
          git commit -m "Automatically update manifest.json" || echo "No changes to commit"
          git push
        
      - name: Deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://connect.fisheries.noaa.gov/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          dir: ./Production/
          access-type: logged_in
          show-logs: true
