name: Deploy App to Posit Connect - PROD
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set Up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
      - name: Install rsconnect
        run: R -e "install.packages('rsconnect')"

      - name: Clean and Snapshot Packrat
        run: |
          R -e "packrat::clean()"
          R -e "packrat::snapshot()"
        
      - name: Write Manifest
        run: R -e "rsconnect::writeManifest(appDir = './Production')"
        
      - name: Deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@${{ secrets.POSIT_CONNECT_URL }}
          dir: ./Production/
          access-type: logged_in
          show-logs: true
          update-env: true

