name: Deploy App to Posit Connect - PROD
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@${{ secrets.POSIT_CONNECT_URL }}
          dir: /Production/
          access-type: logged_in
          show-logs: true
          update-env: true
